"""Chrome Companion native-host registration (BROWSER-COMPANION-01A).

Generates machine-specific runtime artifacts at install time -- never
tracked in git:

    <data_dir>/chrome_companion/install.json
    <data_dir>/chrome_companion/native_host/host_config.json
    <data_dir>/chrome_companion/native_host/lumina-chrome-companion-host  (launcher)
    <chrome user data dir>/NativeMessagingHosts/org.lumina.chrome_companion.json

THE INSTALLER DOES NOT TRUST PATHNAMES (R3 / B3-R3). Each directory it
writes into -- <data_dir>/chrome_companion, its native_host/, and Chrome's
NativeMessagingHosts, the one location outside Lumina's private tree -- is
opened ONCE by state.open_trusted_dir's descriptor walk (every component
opened relative to its parent without following a link, checked on the
object opened; see chrome_companion/state.py), and every artifact is then
written through THAT descriptor (state.write_file_at): never through a
predictable temp name, never following a link, never by reopening a path.
A hostile directory chain is refused, not repaired.

The data dir reaches that walk AS GIVEN (R4 / AR4): it is made absolute,
never resolved, so a link on its path -- and the directory holding that
link -- is checked like any other component, and the paths recorded in the
launcher and Chrome's manifest are the ones the walk vetted.

Only Google Chrome's user-level NativeMessagingHosts directory is ever
written. Firefox (~/.mozilla/native-messaging-hosts) and every other browser
are out of scope by design: Firefox is the owner's browser, not Lumina's.

The Chrome extension itself cannot be installed by this code. Branded Chrome
removed --load-extension (Chrome 137+); the owner loads it once via
chrome://extensions -> Developer mode -> Load unpacked, then passes the
resulting extension ID here.
"""
from __future__ import annotations

import json
import os
import shlex
import stat
import sys
from pathlib import Path

from chrome_companion import protocol, state

NATIVE_HOST_DIRNAME = "native_host"
HOST_CONFIG_FILENAME = "host_config.json"
LAUNCHER_FILENAME = "lumina-chrome-companion-host"
HOST_SCRIPT = Path(__file__).resolve().with_name("native_host.py")


def chrome_user_data_dir() -> Path:
    """Google Chrome's default user data dir on Linux. Chrome honours
    CHROME_CONFIG_HOME, then XDG_CONFIG_HOME, then ~/.config."""
    base = os.environ.get("CHROME_CONFIG_HOME") or os.environ.get("XDG_CONFIG_HOME")
    return (Path(base) if base else Path.home() / ".config") / "google-chrome"


def host_manifest_path(chrome_dir: Path | None = None) -> Path:
    return Path(chrome_dir or chrome_user_data_dir()) / "NativeMessagingHosts" / f"{protocol.HOST_NAME}.json"


def native_host_dir(data_dir) -> Path:
    return state.companion_dir(data_dir) / NATIVE_HOST_DIRNAME


def install(data_dir, *, extension_id: str, chrome_dir: Path | None = None,
            python_executable: str | None = None) -> dict:
    if not protocol.is_extension_id(extension_id):
        raise state.StateError("extension ID must be 32 characters a-p (copy it from chrome://extensions)")
    # Never resolved (R4 / AR4): the walk must see the data dir's own chain.
    data_dir = state.absolute_path(data_dir)
    python_executable = python_executable or sys.executable
    origin = protocol.extension_origin(extension_id)
    host_dir = native_host_dir(data_dir)
    config_path = host_dir / HOST_CONFIG_FILENAME
    launcher = host_dir / LAUNCHER_FILENAME
    manifest_path = host_manifest_path(chrome_dir)
    launcher_text = (
        "#!/bin/sh\n"
        "# Generated by scripts/chrome_companion_setup.py install -- Lumina Chrome Companion\n"
        "# native host launcher. Chrome passes the calling extension origin as $1.\n"
        f"exec {shlex.quote(python_executable)} {shlex.quote(str(HOST_SCRIPT))} "
        f"--config {shlex.quote(str(config_path))} \"$@\"\n"
    )
    manifest = {
        "name": protocol.HOST_NAME,
        "description": "Lumina Chrome Companion (read-only native messaging host)",
        "path": str(launcher),
        "type": "stdio",
        "allowed_origins": [origin],
    }

    # Every directory is opened once and held; every write goes through it.
    companion_fd = state.open_companion_dir(data_dir, create=True)
    try:
        socket_path = state.default_socket_path(companion_fd, data_dir)
        host_fd = state.open_private_subdir(companion_fd, NATIVE_HOST_DIRNAME, create=True, path=host_dir)
        try:
            state.write_private_json_at(host_fd, HOST_CONFIG_FILENAME, {
                "version": state.STATE_VERSION, "extension_origin": origin, "socket_path": socket_path,
            }, path=config_path)
            state.write_file_at(host_fd, LAUNCHER_FILENAME, launcher_text.encode("utf-8"), mode=0o700,
                                path=launcher)
        finally:
            os.close(host_fd)
        registry_fd = state.open_trusted_dir(manifest_path.parent, create=True, private=False)
        try:
            state.write_file_at(registry_fd, manifest_path.name,
                                (json.dumps(manifest, indent=2) + "\n").encode("utf-8"), mode=0o600,
                                path=manifest_path)
        finally:
            os.close(registry_fd)
        record = state.save_install_at(companion_fd, data_dir, extension_id=extension_id, socket_path=socket_path)
    finally:
        os.close(companion_fd)
    return {
        "extension_origin": record.extension_origin, "socket_path": socket_path,
        "host_manifest": str(manifest_path), "launcher": str(launcher),
        "host_config": str(config_path),
    }


def _remove_own_manifest(manifest_path: Path, launcher: Path) -> bool:
    """Unlink the Chrome host manifest only if it is a regular file this user
    owns, in a directory nobody else can write (reached by the descriptor
    walk), registering THIS launcher. Never follows a link, never blocks on a
    planted FIFO."""
    try:
        dir_fd = state.open_trusted_dir(manifest_path.parent, private=False)
    except state.StateError:
        return False
    try:
        try:
            fd = os.open(manifest_path.name, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK
                         | getattr(os, "O_CLOEXEC", 0), dir_fd=dir_fd)
        except OSError:
            return False
        try:
            info = os.fstat(fd)
            if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid():
                return False
            raw = os.read(fd, 64 * 1024)
        finally:
            os.close(fd)
        try:
            manifest = json.loads(raw.decode("utf-8"))
        except ValueError:
            return False
        if not isinstance(manifest, dict) or manifest.get("path") != str(launcher):
            return False
        os.unlink(manifest_path.name, dir_fd=dir_fd)
        return True
    finally:
        os.close(dir_fd)


def uninstall(data_dir, *, chrome_dir: Path | None = None) -> list[str]:
    """Remove only artifacts this installer owns, each through its anchored
    directory. The Chrome host manifest is removed only when it points at
    THIS data dir's launcher; a private directory that is missing, a link, or
    otherwise untrusted is left alone."""
    removed = []
    data_dir = state.absolute_path(data_dir)  # never resolved (R4 / AR4)
    try:
        prior_install = state.load_install(data_dir)
    except state.StateError:
        prior_install = None  # retain the existing hostile-path uninstall refusal
    host_dir = native_host_dir(data_dir)
    manifest_path = host_manifest_path(chrome_dir)
    if _remove_own_manifest(manifest_path, host_dir / LAUNCHER_FILENAME):
        removed.append(str(manifest_path))
    try:
        companion_fd = state.open_companion_dir(data_dir, create=False)
    except state.StateError:
        return removed
    try:
        try:
            host_fd = state.open_private_subdir(companion_fd, NATIVE_HOST_DIRNAME, create=False, path=host_dir)
        except state.StateError:
            host_fd = None
        if host_fd is not None:
            try:
                for name in (LAUNCHER_FILENAME, HOST_CONFIG_FILENAME):
                    if state.remove_regular_at(host_fd, name):
                        removed.append(str(host_dir / name))
            finally:
                os.close(host_fd)
        for name in (state.INSTALL_FILENAME, state.PAIRING_FILENAME):
            if state.remove_regular_at(companion_fd, name):
                removed.append(str(state.companion_dir(data_dir) / name))
    finally:
        os.close(companion_fd)
    from chrome_companion.owner_control import retire_live_connection
    try:
        retire_live_connection(prior_install.socket_path if prior_install else None, "uninstalled")
    except OSError as exc:
        raise state.StateError(f"uninstalled but live connection retirement was not confirmed: {exc}") from exc
    return removed
